#!/bin/bash

 # SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 # SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 #
 # NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 # property and proprietary rights in and to this material, related
 # documentation and any modifications thereto. Any use, reproduction,
 # disclosure or distribution of this material and related documentation
 # without an express license agreement from NVIDIA CORPORATION or
 # its affiliates is strictly prohibited.

# 8 node CXL
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats85.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PAD_no_local_wt -o "-w 0 -r 1 -n 8 -c 8 -t 8 -p 1" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log85.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stat86.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PR_no_local_wt -o "-w 0 -r 1 -n 8 -c 8 -t 8 -f /artifact_top/DO_gem5/datasets/wing_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log86.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats87.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/SSSP_no_local_wt -o "-w 0 -r 1 -n 8 -c 8 -t 8 -l 1 -u 64 -b 32 -f /artifact_top/DO_gem5/datasets/olesnik0_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log87.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats88.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/run_alltoall -o "-w 0 -r 10 -n 8 -c 8 -t 8 -f 128 -s 8 -v 0 -b 0" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log88.txt &

# 8 node UPI
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats89.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PAD_no_local_wt -o "-w 0 -r 1 -n 8 -c 8 -t 8 -p 1" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log89.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats90.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PR_no_local_wt -o "-w 0 -r 1 -n 8 -c 8 -t 8 -f /artifact_top/DO_gem5/datasets/wing_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log90.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats91.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/SSSP_no_local_wt -o "-w 0 -r 1 -n 8 -c 8 -t 8 -l 1 -u 64 -b 32 -f /artifact_top/DO_gem5/datasets/olesnik0_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log91.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats92.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/run_alltoall -o "-w 0 -r 10 -n 8 -c 8 -t 8 -f 128 -s 8 -v 0 -b 0" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log92.txt &

# 4 node CXL
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats93.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PAD_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -p 1" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log93.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats94.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PR_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -f /artifact_top/DO_gem5/datasets/wing_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log94.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats95.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/SSSP_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -l 1 -u 64 -b 32 -f /artifact_top/DO_gem5/datasets/olesnik0_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log95.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats96.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/run_alltoall -o "-w 0 -r 10 -n 4 -c 8 -t 8 -f 128 -s 8 -v 0 -b 0" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log96.txt &

# 4 node UPI
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats97.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PAD_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -p 1" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log97.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats98.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PR_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -f /artifact_top/DO_gem5/datasets/wing_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log98.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats99.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/SSSP_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -l 1 -u 64 -b 32 -f /artifact_top/DO_gem5/datasets/olesnik0_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log99.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats100.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/run_alltoall -o "-w 0 -r 10 -n 4 -c 8 -t 8 -f 128 -s 8 -v 0 -b 0" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log100.txt &

# 2 node CXL
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats101.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PAD_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -p 1" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log101.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats102.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PR_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -f /artifact_top/DO_gem5/datasets/wing_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log102.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats103.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/SSSP_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -l 1 -u 64 -b 32 -f /artifact_top/DO_gem5/datasets/olesnik0_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log103.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats104.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 150 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/run_alltoall -o "-w 0 -r 10 -n 4 -c 8 -t 8 -f 128 -s 8 -v 0 -b 0" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log104.txt &

# 2 node UPI
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats105.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PAD_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -p 1" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log105.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats106.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/PR_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -f /artifact_top/DO_gem5/datasets/wing_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log106.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI/gem5.opt --stats-file=stats107.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/SSSP_no_local_wt -o "-w 0 -r 1 -n 4 -c 8 -t 8 -l 1 -u 64 -b 32 -f /artifact_top/DO_gem5/datasets/olesnik0_out.csr" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log107.txt &
nohup /artifact_top/alloy-gem5/build/RISCV_DO_MESI_64B/gem5.opt --stats-file=stats108.txt --debug-flags=DOSTORAGE --listener-mode=off /artifact_top/alloy-gem5/configs/brg/sc3.py --cpu-type TimingSimpleCPU --link-latency 20 --CG_link_latency 50 --garnet-deadlock-threshold 100000 --l2_size 16384kB --l2_assoc 8 --num-dirs 8 --brg-fast-forward --num-cpus 64 --network garnet2.0 --buffer-size 0 --mem-size 16GB --ruby --l1d_size 64kB --mem-type SimpleMemory --num-l1-cache-ports 8 --num-l2caches 8 --ports 16 --l1i_size 64kB --topology TwoMeshXY -c /artifact_top/alloy-apps/build-applrts_sc3/run_alltoall -o "-w 0 -r 10 -n 4 -c 8 -t 8 -f 128 -s 8 -v 0 -b 0" --vcs-per-vnet 64 --buffers-per-data-vc 65536 --buffers-per-ctrl-vc 1024 > logs/log108.txt &

wait